export const employees = [
  {
    id: 1,
    name: "Sara Ahmed",
    email: "sara@nexora.com",
    department: "Human Resources",
    role: "HR Manager",
    status: "Active",
  },
  {
    id: 2,
    name: "Omar Khaled",
    email: "omar@nexora.com",
    department: "Engineering",
    role: "Frontend Developer",
    status: "Active",
  },
  {
    id: 3,
    name: "Lina Saleh",
    email: "lina@nexora.com",
    department: "Marketing",
    role: "Content Strategist",
    status: "On Leave",
  },
  {
    id: 4,
    name: "Yousef Nasser",
    email: "yousef@nexora.com",
    department: "Finance",
    role: "Accountant",
    status: "Inactive",
  },
  {
    id: 5,
    name: "Maya Ali",
    email: "maya@nexora.com",
    department: "Engineering",
    role: "Backend Developer",
    status: "Active",
  },
];

export const departments = [
  {
    id: 1,
    name: "Engineering",
    manager: "Omar Khaled",
    employeesCount: 24,
    activeProjects: 7,
    budget: 120000,
    status: "Active",
  },
  {
    id: 2,
    name: "Human Resources",
    manager: "Sara Ahmed",
    employeesCount: 8,
    activeProjects: 3,
    budget: 45000,
    status: "Active",
  },
  {
    id: 3,
    name: "Marketing",
    manager: "Lina Saleh",
    employeesCount: 14,
    activeProjects: 5,
    budget: 70000,
    status: "Active",
  },
  {
    id: 4,
    name: "Finance",
    manager: "Yousef Nasser",
    employeesCount: 10,
    activeProjects: 2,
    budget: 95000,
    status: "Review",
  },
  {
    id: 5,
    name: "Engineering",
    manager: "Omar Khaled",
    employeesCount: 24,
    activeProjects: 7,
    budget: 120000,
    status: "Active",
  },
  {
    id: 6,
    name: "Human Resources",
    manager: "Sara Ahmed",
    employeesCount: 8,
    activeProjects: 3,
    budget: 45000,
    status: "Active",
  },
];

export const projects = [
  {
    id: 1,
    name: "HR Management System",
    client: "Internal Company",
    manager: "Hassan Emawe",
    status: "In Progress",
    priority: "High",
    progress: 72,
    dueDate: "2026-06-18",
  },
  {
    id: 2,
    name: "Customer Portal",
    client: "Nexora Clients",
    manager: "Omar Akar",
    status: "Planning",
    priority: "Medium",
    progress: 35,
    dueDate: "2026-07-10",
  },
  {
    id: 3,
    name: "oday Dashboard",
    client: "Engnering Department",
    manager: "Oday Saad",
    status: "Completed",
    priority: "Low",
    progress: 100,
    dueDate: "2026-05-20",
  },
  {
    id: 4,
    name: "Mobile Employee App",
    client: "HR Department",
    manager: "Mohanaed Talat",
    status: "In Progress",
    priority: "High",
    progress: 58,
    dueDate: "2026-06-01",
  },
];

export const reports = [
  {
    id: 1,
    title: "Monthly Performance Report",
    type: "Performance",
    department: "All Departments",
    status: "Ready",
    date: "2026-05-25",
    score: 86,
  },
  {
    id: 2,
    title: "Engineering Productivity",
    type: "Productivity",
    department: "Engineering",
    status: "Ready",
    date: "2026-05-22",
    score: 78,
  },
  {
    id: 3,
    title: "Marketing Campaign Results",
    type: "Marketing",
    department: "Marketing",
    status: "Draft",
    date: "2026-05-18",
    score: 64,
  },
  {
    id: 4,
    title: "Financial Overview",
    type: "Finance",
    department: "Finance",
    status: "Ready",
    date: "2026-05-15",
    score: 91,
  },

  {
    id: 5,
    title: "Monthly Performance Report",
    type: "Performance",
    department: "All Departments",
    status: "Ready",
    date: "2026-05-25",
    score: 86,
  },
];
export const tasks = [
  {
    id: 1,
    title: "Prepare employee onboarding document",
    project: "HR Management System",
    owner: "Sara Ahmed",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-06-02",
  },
  {
    id: 2,
    title: "Design dashboard analytics cards",
    project: "Finance Dashboard",
    owner: "Omar Khaled",
    status: "Pending",
    priority: "Medium",
    dueDate: "2026-06-05",
  },
  {
    id: 3,
    title: "Fix login validation messages",
    project: "Customer Portal",
    owner: "Maya Ali",
    status: "Completed",
    priority: "Low",
    dueDate: "2026-05-28",
  },
  {
    id: 4,
    title: "Review mobile app navigation flow",
    project: "Mobile Employee App",
    owner: "Lina Saleh",
    status: "Pending",
    priority: "High",
    dueDate: "2026-06-01",
  },
];